#port
server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://aws-free-rds.ch4qqwi8o8lu.ap-northeast-2.rds.amazonaws.com:3306/sixsenses
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sixsense.qna
    password: Sixsenseqna1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com.likelion.sixsenses: debug
